from backend.prompts.aptitude_prompts import APTITUDE_GENERATION_PROMPT, APTITUDE_EXPLANATION_PROMPT
from backend.prompts.gd_prompts import GD_TOPIC_PREP_PROMPT, GD_SIMULATION_TURN_PROMPT, GD_EVALUATION_PROMPT
from backend.prompts.interview_prompts import (
    INTERVIEWER_SYSTEM_PROMPT,
    INTERVIEW_QUESTION_GEN_PROMPT,
    INTERVIEW_EVALUATION_PROMPT,
    INTERVIEW_FINAL_REPORT_PROMPT
)
from backend.prompts.resume_prompts import RESUME_PARSING_PROMPT, RESUME_QUESTIONS_PROMPT
from backend.prompts.recommendation_prompts import RECOMMENDATION_PROMPT

__all__ = [
    "APTITUDE_GENERATION_PROMPT", "APTITUDE_EXPLANATION_PROMPT",
    "GD_TOPIC_PREP_PROMPT", "GD_SIMULATION_TURN_PROMPT", "GD_EVALUATION_PROMPT",
    "INTERVIEWER_SYSTEM_PROMPT", "INTERVIEW_QUESTION_GEN_PROMPT",
    "INTERVIEW_EVALUATION_PROMPT", "INTERVIEW_FINAL_REPORT_PROMPT",
    "RESUME_PARSING_PROMPT", "RESUME_QUESTIONS_PROMPT",
    "RECOMMENDATION_PROMPT"
]
